{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "jena-fuseki.fullname" . }}
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "jena-fuseki.selectorLabels" . | nindent 6 }}
  template:
    {{- include "jena-fuseki.podTemplate" . | nindent 6 }}
{{- end }}
