{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jena-fuseki.fullname" . }}
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jena-fuseki.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    {{- include "jena-fuseki.podTemplate" . | nindent 6 }}
{{- end }}
