apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jena-fuseki.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "jena-fuseki.fullname" . }}
                port:
                  number: 3030
            path: /
            pathType: Prefix