apiVersion: v2
name: jena
description: Apache Jena Fuseki is a SPARQL server
type: application
version: "0.0.0"
appVersion: "0.0.0"

dependencies:
  - name: library-chart
    version: 2.0.20
    repository: https://inseefrlab.github.io/helm-charts-datascience